# Generated by Django 4.0.2 on 2022-04-03 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0005_remove_contact_unique_user_name_number_and_more'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledmessage',
            name='user',
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='last_modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='reference_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.event'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
