# Generated by Django 4.0.2 on 2022-03-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='detail',
            field=models.TextField(default='Manually filled contact'),
        ),
    ]
